### ISSUE TITLE
No issue, just wanted to say thank you!

### ISSUE THREAD

**Issue by Benimautner** [johnmave126/avgps#1]
I've been searching for hours for a solution to share GPS to my iPad. Thank you so much for building a clean and simple app that just works! Just trying to spread some love so maybe this repo gets more traffic :)

**Comment by johnmave126** [comment]
Glad you like it! Just a heads up, make sure to turn off battery optimization on the app, otherwise the system might occasionally terminate the background task while in flight (happened to me a few times).
