### ISSUE TITLE
Feature Request: Bluetooth 

### ISSUE THREAD

**Issue by bfransoo** [johnmave126/avgps#2]
Hey, this worked fine on hotspot from my S24+ to iPad mini 5 (17.5.1). 
Could it be possible to send the location data to ForeFlight over a Bluetooth connection, instead of the wifi tether?

**Comment by johnmave126** [comment]
Unfortunately, iOS only works with bluetooth gps receiverr with an MFi certificate, and there is no way I could spoof an Android phone as one.
